# 使用官方的 Tomcat 镜像，并指定一个带有 JRE 8 的版本，以确保兼容性
FROM tomcat:9.0-jre8

# 移除 Tomcat webapps 目录中默认的 ROOT 应用
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# 将当前目录下的所有文件复制到 Tomcat 的 webapps/ROOT 目录中
COPY . /usr/local/tomcat/webapps/ROOT
